version: "3.8"

services:
  web:
    build: .
    container_name: portfolio_site
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./flask_session:/app/flask_session
      - ./secret.key:/app/secret.key
    environment:
      FLASK_ENV: production
      GITHUB_TOKEN: ${GITHUB_TOKEN}